meta_name: "Stop debates between flatmates"
meta_title: "Timoty App"
meta_description: "Complete your tasks to earn points, get extra points for speed or do something nice for your flatmates to get tips. Anything to win!"
meta_image: "cover.png" # should exist in `app/assets/images/`
